import turtle
screen = turtle.Screen()
screen.bgcolor("skyblue")

pen = turtle.Turtle()
pen.pensize(3)
pen.speed(3)
pen.penup()
pen.goto(-100, -100)
pen.pendown()
pen.color("black", "orange")
pen.begin_fill()
for _ in range(4):
    pen.forward(200)
    pen.left(90)
pen.end_fill()
pen.color("black", "brown")
pen.begin_fill()
pen.goto(-100, 100)
pen.goto(0, 200)
pen.goto(100, 100)
pen.goto(-100, 100)
pen.end_fill()

pen.penup()
pen.goto(-30, -100)
pen.pendown()
pen.color("black", "darkred")
pen.begin_fill()
pen.goto(-30, 50)
pen.goto(30, 50)
pen.goto(30, -100)
pen.goto(-30, -100)
pen.end_fill()

pen.penup()
pen.goto(-80, 20)
pen.pendown()
pen.color("black", "lightblue")
pen.begin_fill()
for _ in range(4):
    pen.forward(30)
    pen.left(90)
pen.end_fill()

pen.penup()
pen.goto(50, 20)
pen.pendown()
pen.color("black", "lightblue")
pen.begin_fill()
for _ in range(4):
    pen.forward(30)
    pen.left(90)
pen.end_fill()
pen.hideturtle()
turtle.done()

